[package]
name = "libtorrent-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
link-cplusplus = "1.0"

[build-dependencies]
bindgen = "0.63.0"
cmake = "0.1"
